ALTER TABLE users ADD COLUMN max_cpu TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN max_memory_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN max_disk_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN max_machine_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN max_snapshot_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE machines ADD COLUMN cpu TEXT NOT NULL DEFAULT '';
ALTER TABLE machines ADD COLUMN memory_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE machines ADD COLUMN disk_bytes INTEGER NOT NULL DEFAULT 0;

ALTER TABLE snapshots ADD COLUMN cpu TEXT NOT NULL DEFAULT '';
ALTER TABLE snapshots ADD COLUMN memory_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE snapshots ADD COLUMN disk_bytes INTEGER NOT NULL DEFAULT 0;
